apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
    openshift.io/generated-by: OpenShiftNewApp
    template.alpha.openshift.io/wait-for-ready: "true"
  generation: 14
  labels:
    app: taiga-back
    template: taiga-back
  name: taiga-back
  namespace: taiga
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: taiga-back
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        name: taiga-back
      name: taiga-back
    spec:
      containers:
      - env:
        - name: DJANGO_SETTINGS_MODULE
          value: openshift
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: taiga-back
        - name: DB_PASSWORD
          value: Redhat1!
        image: taiga-back
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: taiga-back
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/lib/python3.6/site-packages/openshift
          name: taiga-settings
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: taiga-settings
        name: taiga-settings
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - taiga-back
      from:
        kind: ImageStreamTag
        name: taiga-back:latest
        namespace: taiga
    type: ImageChange
  - type: ConfigChange
